pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    docker.image('node:18').inside {
                        sh 'npm install'
                    }
                }
            }
        }

        stage('Run Application') {
            steps {
                script {
                    docker.image('node:18').inside {
                        sh 'node app.js'
                    }
                }
            }
        }
    }
}
